// These styles apply to every route in the application
import Footer from "../layout/Footer";
import Header from "../layout/Header";
import "./globals.css";

export const metadata = {
  title: "HYPERAS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <html lang="en">
    //   <body>
    //     {" "}
    //     <Header />
    //     {children}
    //     <Footer />
    //   </body>
    // </html>

    <div>
      {" "}
      <Header />
      {children}
      <Footer />
    </div>
  );
}
